# Algebra Linear com NumPy
## Andre Nepomuceno - UFF

**1. Multiplicação de Matrizes**

In [1]:
import numpy as np

In [2]:
A = np.array([[0,0.5], [-1,2]])
B = np. array([[2, -0.5] , [3, 1.5]])
A

array([[ 0. ,  0.5],
       [-1. ,  2. ]])

In [3]:
A*5

array([[ 0. ,  2.5],
       [-5. , 10. ]])

In [4]:
np.dot(A,B)  #ou A @ B

array([[1.5 , 0.75],
       [4.  , 3.5 ]])

In [5]:
A*B

array([[ 0.  , -0.25],
       [-3.  ,  3.  ]])

In [6]:
A.T   #ou A.transpose()

array([[ 0. , -1. ],
       [ 0.5,  2. ]])

In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.linalg.matrix_power(A,3)

array([[-1.  ,  1.75],
       [-3.5 ,  6.  ]])

In [9]:
A**3

array([[ 0.   ,  0.125],
       [-1.   ,  8.   ]])

**2. Normas e Rank**

In [10]:
np.linalg.norm(A)

2.29128784747792

In [11]:
c = np.array([1,2j,1-1j])
np.linalg.norm(c)

2.6457513110645907

In [12]:
np.linalg.matrix_rank(A)

2

In [13]:
D = np.array([[1,1], [2 ,2]])
D

array([[1, 1],
       [2, 2]])

In [14]:
np.linalg.matrix_rank(D)

1

**3. Determinante, Traço e Inversa**

In [15]:
np.linalg.det(A)

0.5

In [16]:
np.trace(A)

2.0

In [17]:
np.linalg.inv(A)

array([[ 4., -1.],
       [ 2.,  0.]])

**4. Autovalores e Autovetores**

In [18]:
#autovalores e autovetores
vals, vecs = np.linalg.eig(A)
print(vals)

[0.29289322 1.70710678]


In [19]:
lamb1, lamb2 = vals
print(lamb1)

0.29289321881345254


In [20]:
#Autovetores
vecs

array([[-0.86285621, -0.28108464],
       [-0.50544947, -0.95968298]])

In [21]:
x1 = vecs[:,0]
print(x1)

[-0.86285621 -0.50544947]


In [22]:
#A matrix vecs é U-1, tal que UAU-1 = diagonal()
u = np.linalg.inv(vecs)
np.dot(u,np.dot(A,vecs))

array([[ 2.92893219e-01, -1.11022302e-16],
       [ 0.00000000e+00,  1.70710678e+00]])

In [23]:
#Verifique que Ax = lambda x
np.dot(A,x1)

array([-0.25272473, -0.14804272])

In [24]:
lamb1*x1

array([-0.25272473, -0.14804272])

**5. Sistemas de Equações Lineares**

In [25]:
M = np.array([ [3., -2, 0], [-2, 1, -3],[4, 6, 1]])
print(M)

[[ 3. -2.  0.]
 [-2.  1. -3.]
 [ 4.  6.  1.]]


In [26]:
b = np.array([8, -20, 7])

In [27]:
x, y, z = np.linalg.solve(M,b)
print('x = {}, y = {}, z = {}'.format(x,y,z))

x = 2.0, y = -1.0, z = 5.0


**Exemplo**

Vamos escrever o sistema na forma matricial (RI = V)
\begin{gather}
\begin{pmatrix}
50 & 0 & -30\\
0 & 40 & -20 \\
-30 & -20 & 100
\end{pmatrix}
\begin{pmatrix}
I_1 \\
I_2 \\
I_3
\end{pmatrix}
= 
\begin{pmatrix}
80\\
80\\
0
\end{pmatrix}
\end{gather}

In [28]:
R = np.array([[50, 0, -30], [0, 40, -20], [-30, -20, 100]])
V = np.array([80,80,0])              

In [29]:
I1, I2, I3 = np.linalg.solve(R,V)
print('I1 = {:.2f} A'.format(I1))
print('I2 = {:.2f} A'.format(I2))
print('I3 = {:.2f} A'.format(I3))

I1 = 2.33 A
I2 = 2.61 A
I3 = 1.22 A
